name: Photoactivation
view: Tab # Tab or Popup if has an GUI

acquisition_modes:
  - name: Photoactivation
    file_name: photoactivation.py

###################################################################
# how to add plugin device in the .navigate/configuration.yaml file
#
# plugin_device:
#   hardware:
#     type: PluginDevice
###################################################################
